@baseUrl=http://localhost:3000

###
GET {{baseUrl}} HTTP/1.1

###
POST {{baseUrl}}/subscribe HTTP/1.1
Content-Type: application/x-www-form-urlencoded
HX-Request: true

email=test{{$randomInt 1 10}}@example.com

###
GET {{baseUrl}}/not-found HTTP/1.1
